config/routes.rb
Rails.application.routes.draw do
  resources :plans do
    get 'report', on: :collection
    post 'report_date', on: :collection
  end
  root 'money#index'

  resources :types
  resources :trans
  resources :cards 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :trans
  def self.totals
    cards=Card.all
    @totals=0
    cards.each do |card|
      @totals=@totals+card.balance
    end
    return @totals
  end
  def balance_change(quality)
    self.balance=self.balance-quality
    self.save
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :type
end

app/models/tran.rb
class Tran < ApplicationRecord
  belongs_to :type
  belongs_to :card
  accepts_nested_attributes_for :type
  accepts_nested_attributes_for :card
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :trans
  has_many :plans
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :find_id, only: [:edit, :update , :destroy]
  def index 
    @cards=Card.all
  end

  def new
    @card=Card.new
  end

  def edit
  end

  def update
    @card.update_attributes card_params
    redirect_to cards_path
  end
  def create
    @card=Card.new(card_params)
    @card.save
    redirect_to cards_path
  end
  def destroy
    @card.destroy
    redirect_to cards_path
  end
  private
  def card_params
    params.require(:card).permit(:name,:balance)
  end
  def find_id
    @card=Card.find(params[:id])
  end
end

app/controllers/money_controller.rb
class MoneyController < ApplicationController
  def index
    @cards=Card.all
    @trans=Tran.order(date: :desc).order(created_at: :desc).first(10)
    @tran=Tran.new
    @totals=Card.totals
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :plan_find, only: [:edit, :update, :destroy]
  def index
    @plans=Plan.all
  end
  def new
    @plan=Plan.new
  end
  def create
    @plan = Plan.create(plan_params)
    redirect_to plans_path
  end
  def edit
  end
  def update
    @plan.update_attributes(plan_params)
    redirect_to plans_path
  end
  def destroy
    @plan.destroy
    redirect_to plans_path
  end
  def report
    @date=Date.today
  end
  def report_date
    @date=params.class
    @date1=[params['per(1i)'].to_i,params['per(2i)'].to_i,params['per(3i)'].to_i]
    render :report
  end
  private
  def plan_params
    params.require(:plan).permit(:date, :type_id, :comment, :quality)
  end
  def date_params
    params.require(:period).permit(:date)
  end
  def plan_find
    @plan=Plan.find_by_id(params[:id])
  end
end

app/controllers/trans_controller.rb
class TransController < ApplicationController
  before_action :find_tran, only: [:edit, :update, :destroy]
  def index
    @trans=Tran.all
  end
  def new
    @tran=Tran.new
  end
  def edit
  end
  def update
    @quality=@tran.quality
   if @tran.update_attributes(tran_params)
    @uality=@tran.quality-@quality
    card=Card.find_by_id(@tran.card_id)
    card.balance_change(@uality)
    redirect_to trans_path
   else
     render :edit
   end
  end

  def create 
   @tran=Tran.new(tran_params)
   if @tran.save
     card=Card.find_by_id(@tran.card_id)
     card.balance_change (@tran.quality)
      redirect_to root_path
   else
     render :edit
   end
  end
  def destroy
    @quality=-@tran.quality
    if @tran.destroy
      card=Card.find_by_id(@tran.card_id)
      card.balance_change(@quality)
      redirect_to trans_path
    else
      redirect_to trans_path§
    end
  end
  private
  def tran_params
    params.require(:tran).permit(:date,:quality,:type_id,:card_id)
  end
  def find_tran
    @tran=Tran.find(params[:id])
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :find_type, only: [:edit, :update, :destroy]
  def index
    @type=Type.all
  end

  def new
    @type=Type.new
  end

  def edit
  end
  def create
    @type=Type.new(type_params)
    @type.save
    redirect_to types_path
  end
  def update
    @type.update_attributes(type_params)
    redirect_to types_path
  end
  def destroy
    @type.destroy
    redirect_to types_path
  end
  private
  def find_type
    @type=Type.find(params[:id])
  end
  def type_params
    params.require(:type).permit(:operation,:debet)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/money_helper.rb
module MoneyHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/trans_helper.rb
module TransHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/cards/_form.html.erb
<div class='col-md-4'>
<%= simple_form_for @card do |f| %>
  <%= f.input :name %>
  <%= f.input :balance %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/cards/edit.html.erb
<h1><%= t('.edit card') %></h1>
<%= render 'form' %>

app/views/cards/index.html.erb
<h1><%= t('.cards') %></h1>
<div class='col-md-4'>
<%= link_to t('common.new'), new_card_path %>
<br />
<table class='table'>

<% @cards.each do |card| %>
  <tr>
    <td><%= card.name %></td>
    <td><%= card.balance %></td>
    <td><%= link_to t('common.edit'), edit_card_path(card) %>
        <%= link_to t('common.destroy'), card, method: :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to t('common.back'), root_path %>
</div>

app/views/cards/new.html.erb
<h1><%= t('.new card') %></h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Money</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container-fluid'>
    <%= yield %>
    </div>
  </body>
</html>

app/views/money/index.html.erb
<h1>Hello Money -))</h1><p>Version 0.1.1<p>
<div class='row'>
  <div class='col-md-3'>
    <table class='table'>
      <% @cards.each do |card| %>
        <tr>
          <td><%= card.name %></td>
          <td><%= card.balance %></td>
        </tr>
        <% end %>
        <tr>
          <td><%= t('.totals')%></td>
          <td><%= @totals %>
      </tr>
    </table>
  </div>
</div>
<hr>
<div class='row'>
  <%= render 'trans/form' %>
  <div class='col-md-8'>
    <table class='table'>
      <tr>
        <td><%= link_to t('.trans'), trans_path %></td>
        <td><%= link_to t('.operations'), types_path %></td>
        <td></td>
        <td><%= link_to t('.cards'), cards_path %></td>
      </tr>
    <% @trans.each do |tran| %>
      <tr>
         <td><%= tran.date %></td>
         <td><%= tran.type.operation %></td>
         <td><%= tran.quality %></td>
         <td><%= tran.card.name %></td>
      </tr>
    <% end %>
  </table>
  </div>
</div>

app/views/plans/_form.html.erb
<div class='col-md-4'>
  <%= @plan %>
<%= simple_form_for @plan do |f| %>
  <%= f.input :date %>
  <%= f.association :type, label_method: :operation, value_method: :id, include_blank: false %>
  <%= f.input :comment %>
  <%= f.input :quality %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/plans/edit.html.erb
<h1>plan edit</h1>
<%= render 'form' %>

app/views/plans/index.html.erb
<h1>Plans#index</h1>
<div class='row'>
<div class='col-md-12'>
<%= link_to t('common.new'), new_plan_path %>
<table class='table'>
<% @plans.each do |plan| %>
  <tr>
    <td><%= plan.date %></td>
    <td><%= plan.type.operation %></td>
    <td><%= plan.comment %></td>
    <td><%= plan.quality %></td>
    <td><%= link_to t('common.edit'), edit_plan_path(plan) %>
    <%= link_to t('common.destroy'), plan, method: :delete %></td>
  </tr>
<% end %>
</table>
</div>
</div>

app/views/plans/new.html.erb
<h1>New plan</h1>
<%= render 'form' %>

app/views/plans/report.html.erb
<h1>Report</h1>
<div class='row'>
  <%= @date %>
  <%= simple_form_for :period, { url: report_date_plans_path } do |f| %>
    <%= f.input :per, as: :date, selected: Date.today, order: [:month, :year] %>
    <%= f.button :submit %>
  <% end%>
</div>

app/views/trans/_form.html.erb
<div class='col-md-3'>
  <%= simple_form_for @tran do |f| %>
    <%= f.input :date %>
    <%= f.association :type, label_method: :operation, value_method: :id, include_blank: false  %>
    <%= f.association :card, label_method: :name, value_method: :id, include_black: false %>
    <%= f.input :quality %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/trans/edit.html.erb
<h1><%= t('.edit tran') %></h1>
<%= render 'form', tran: @tran %>

app/views/trans/index.html.erb
<h1><%= t('.trans') %></h1>
<div class='col-md-10'>
  <%= link_to t('common.new'), new_tran_path %>
  <table class='table'>
    <% @trans.each do |tran| %> 
      <tr>
        <td><%= tran.date %></td>
        <td><%= tran.type.operation %></td>
        <td><%= tran.quality %></td>
        <td><%= tran.card.name %></td>
        <td><%= link_to t('common.edit'), edit_tran_path(tran) %>
        <%= link_to t('common.destroy'), tran, method: :delete %></td>
      </tr>
<% end %>
  </table>
  <%= link_to t('common.back'), root_path %>
</div>

app/views/trans/new.html.erb
<h1><%= t('.new tran') %></h1>
<%= render 'form' , tran: @tran %>

app/views/types/_form.html.erb
<div class='col-md-4'>
<%= simple_form_for @type, html: { class: "form-horizontal"} do |f| %>
  <%= f.input :operation %>
  <%= f.input :debet %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/types/edit.html.erb
<h1><%= t('.edit type') %></h1>
<%= render 'form' %>

app/views/types/index.html.erb
<h1><%= t('.types') %></h1>
<div class='col-md-8'>
  <%= link_to t('common.new'), new_type_path %>
  <table class='table'>
    <% @type.each do |type| %>
      <tr>
        <td><%= type.operation %></td>
        <td><%= type.debet %></td>
        <td><%= link_to t('common.edit'), edit_type_path(type) %>
        <%= link_to t('common.destroy'), type, method: :delete %></td>
<% end %>
  </table>
  <%= link_to t('common.back'), root_path %>
</div>

app/views/types/new.html.erb
<h1><%= t('.new type') %></h1>
<%= render 'form' %>